spring.application.name=creatorstore

# DataBase information
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Hibernate ORM configuration
#Hibernate to automatically update your database schema to match your entity classes when the app starts. update is fine for development. Use none or validate in production.
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 

# swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Errors
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always




